apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-paths

spec:
  rules:
    - host: www.matsishin-test.net
      http:
        paths:
          - path: "/page1"
            backend:
              serviceName: my-api-service
              servicePort: 8080