apiVersion: v1
kind: Pod
metadata:
  name: my-backend
  labels:
    app: backend
    rel: stable
spec:
  containers:
    - name: backend
      image: docker.io/matsishin/kuber-backend:0.2.2
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /actuator/health/liveness
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /actuator/health/readiness
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5