apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling-{{ .Release.Name}}
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: backend-{{.Release.Name}}
  minReplicas: {{ .Values.scaling.minReplicaCount}}
  maxReplicas: {{ .Values.scaling.maxReplicaCount}}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80